spring.application.name=critcpoint
spring.datasource.url=jdbc:postgresql://localhost:5433/critcpoint
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=critcpoint@gmail.com
spring.mail.password=aawx wvbq orwz trme
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true